In [1]:
import numpy as np

 __1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:
 
 а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

In [31]:
A = np.array([[8, 5], [4, 6], [0, 11], [2, 7]])
B = np.array([[5, 2], [5, 7], [3, 13], [22, 4]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 8  5]
 [ 4  6]
 [ 0 11]
 [ 2  7]]
Матрица B
[[ 5  2]
 [ 5  7]
 [ 3 13]
 [22  4]]


ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

In [30]:
A2 = np.array([[8, 5, 6, 7, 12], [4, 6, 0, 4, 11]])
B2 = np.array([[5, 2, 3], [5, 7, 4], [3, 13, 1], [22, 4, 5], [2, 5, 9]])

print(f'Матрица A\n{A2}')
print(f'Матрица B\n{B2}')
print(f'Матрица AB\n{np.dot(A2, B2)}')

Матрица A
[[ 8  5  6  7 12]
 [ 4  6  0  4 11]]
Матрица B
[[ 5  2  3]
 [ 5  7  4]
 [ 3 13  1]
 [22  4  5]
 [ 2  5  9]]
Матрица AB
[[261 217 193]
 [160 121 155]]


   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

In [29]:
A3 = np.array([[5, 2, 3], [5, 7, 4], [3, 13, 1], [22, 4, 5], [2, 5, 9], [5, 7, 4], [3, 13, 1], [22, 4, 5]])
B3 = np.array([[8, 5, 6, 7, 12, 8, 9, 10], [4, 6, 0, 4, 11, 33, 11, 14], [4, 6, 0, 4, 11, 54, 5, 8]])

print(f'Матрица A\n{A3}')
print(f'Матрица B\n{B3}')
print(f'Матрица AB\n{np.dot(A3, B3)}')

Матрица A
[[ 5  2  3]
 [ 5  7  4]
 [ 3 13  1]
 [22  4  5]
 [ 2  5  9]
 [ 5  7  4]
 [ 3 13  1]
 [22  4  5]]
Матрица B
[[ 8  5  6  7 12  8  9 10]
 [ 4  6  0  4 11 33 11 14]
 [ 4  6  0  4 11 54  5  8]]
Матрица AB
[[ 60  55  30  55 115 268  82 102]
 [ 84  91  30  79 181 487 142 180]
 [ 80  99  18  77 190 507 175 220]
 [212 164 132 190 363 578 267 316]
 [ 72  94  12  70 178 667 118 162]
 [ 84  91  30  79 181 487 142 180]
 [ 80  99  18  77 190 507 175 220]
 [212 164 132 190 363 578 267 316]]


 г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

In [32]:
A4 = np.array([[8, 5, 5, 5], [4, 6, 4, 4], [0, 11, 12, 66], [2, 7, 1, 1]])
B4 = np.array([[5, 2, 7, 7], [5, 7, 8, 9], [3, 13, 55, 100], [22, 4, 4, 99]])

print(f'Матрица A\n{A4}')
print(f'Матрица B\n{B4}')
print(f'Матрица AB\n{np.dot(A4, B4)}')

Матрица A
[[ 8  5  5  5]
 [ 4  6  4  4]
 [ 0 11 12 66]
 [ 2  7  1  1]]
Матрица B
[[  5   2   7   7]
 [  5   7   8   9]
 [  3  13  55 100]
 [ 22   4   4  99]]
Матрица AB
[[ 190  136  391 1096]
 [ 150  118  312  878]
 [1543  497 1012 7833]
 [  70   70  129  276]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [35]:
A5 = np.array([[1, -2], [3, 0]])
B5 = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A5}')
print(f'Матрица B\n{B5}')
print(f'Сложение Матриц A + B\n{A5 + B5}')
print(f' Произведение Матриц AB\n{np.dot(A5, B5)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Сложение Матриц A + B
[[ 5 -3]
 [ 3  5]]
 Произведение Матриц AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [2]:
A6 = np.array([[1, 7], [3, -6]])
B6 = np.array([[0, 5], [2, -1]])
C6 = np.array([[2, -4], [1, 1]])

k = 3
n = 2
m = 4

print(f'Матрица 3А-2B+4C\n{k*A6 - n*B6 + m*C6}')

Матрица 3*А
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [6]:
A7 = np.array([[4, 1], [5, -2], [2, 3]])
A8 = A7.T

q = np.dot(A7, A8)
i = np.dot(A8, A7)

print(f'Матрица:\n{A7}')
print(f'Транспонированная матрица:\n{A8}')
print(f'Матрица A*A^T:\n{q}')
print(f'Матрица A^T*A:\n{i}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*A^T:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^T*A:
[[45  0]
 [ 0 14]]
